# Generated by Django 4.2.5 on 2023-09-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(default='noticia', max_length=40),
        ),
    ]
