# Generated by Django 4.2.5 on 2023-09-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.TextField(default='noticia', max_length=200),
        ),
    ]
