# Generated by Django 4.2.5 on 2023-10-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_noticia_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='tags',
            field=models.CharField(choices=[('Nacion', 'Nacion'), ('Industria', 'Industria'), ('Economia', 'Economia'), ('Deportes', 'Deportes'), ('Farandula', 'Farandula'), ('Política', 'Política'), ('Mundo', 'Mundo'), ('Opinion', 'Opinion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('saved_news', models.ManyToManyField(to='main.noticia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
