# Generated by Django 4.2.5 on 2023-10-13 02:01

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_noticia_contenido_alter_noticia_resumen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferences',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Nacion', 'Nacion'), ('Industria', 'Industria'), ('Economia', 'Economia'), ('Deportes', 'Deportes'), ('Farandula', 'Farandula'), ('Política', 'Política'), ('Mundo', 'Mundo'), ('Opinion', 'Opinion')], default=['mundo'], max_length=50),
            preserve_default=False,
        ),
    ]
