# Generated by Django 4.2.5 on 2023-10-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customuser_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Na', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
