# Generated by Django 4.2.5 on 2023-10-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_groups_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default='pass', max_length=20),
            preserve_default=False,
        ),
    ]
