# Generated by Django 4.2.5 on 2023-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/pfp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saved_news',
            field=models.ManyToManyField(blank=True, to='main.noticia'),
        ),
    ]
