# Generated by Django 4.2.4 on 2023-10-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_customuser_profile_pic_alter_customuser_saved_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
